### ISSUE TITLE
BUG - Authentication with username (not email)

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#30]
By using a non-email-address as username (example: user instead of user@nomail.org) the authentication module of API crashes in a very bad way:

```
2017-07-06 08:01:59,318 [ERROR   rapydo.services.authentication:98] Broken auth backend:
[<class 'neomodel.exception.DeflateError'>] Attempting to deflate property 'email' on None of class 'User': 'pippo' does not matches '[^@]+@[^@]+\\.[^@]+'
2017-07-06 08:01:59,319 [CRITICAL rapydo.services.authentication:99] Please reinitialize backend tables
2017-07-06 08:01:59,319 [WARNING rapydo.decorators:252] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/rapydo/decorators.py", line 245, in wrapper
    out = func(self, *args, **kwargs)
    │     │    │      │       └ {}
    │     │    │      └ ()
    │     │    └ <rapydo.resources.endpoints.Login object at 0x7fe258088828>
    │     └ <function Login.post at 0x7fe259fb99d8>
    └ None
  File "/usr/local/lib/python3.6/dist-packages/rapydo/resources/endpoints.py", line 119, in post
    token, jti = self.auth.make_login(username, password)
                 │                    │         └ 'pluto'
                 │                    └ 'pippo'
                 └ <rapydo.resources.endpoints.Login object at 0x7fe258088828>
  File "/usr/local/lib/python3.6/dist-packages/rapydo/services/authentication/__init__.py", line 103, in make_login
    status_code=hcodes.HTTP_SERVER_ERROR
                └ <module 'rapydo.utils.htmlcodes' from '/usr/local/lib/python3.6/dist-packages/rapydo/utils/htmlcodes.py'>
rapydo.exceptions.RestApiException: Server authentication misconfiguration

2017-07-06 08:01:59,320 [ERROR   rapydo.decorators:217] Server authentication misconfiguration
2017-07-06 08:01:59,320 [ERROR   rapydo.rest.definition:336] ['Server authentication misconfiguration']

```

I verified this problem using neo4j, I don't known if other databases have the same problem

I will add a custom unit test and I will fix for neo4j, to be verified for sql and mongo

**Comment by mdantonio** [comment]
@pdonorio have you tested this bug on sqlalchemy?

**Comment by pdonorio** [comment]
Just tested. It works without changes, my sql field is not strictly related to the email format. Mongo too, being nosql with no schema has no problems on this.
