### ISSUE TITLE
Backend unable to re-create neo4j connection once lost

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#73]
How to reproduce:

- start the stack
- stop neo4j
- obtain connection errors from backend
- restart neo4j
- backend is still in error

**Comment by pdonorio** [comment]
Is this depending on how neomodel handles the connection?

**Comment by mdantonio** [comment]
I still don't know, maybe

**Comment by mdantonio** [comment]
The problem occurred again yesterday

But I'm unable to reproduce the error by following the list of operation reported in this issue, so we still have to understand what is really causing the problem

**Comment by mdantonio** [comment]
The problem here is related to authentication module since the reference to the database connection is static:

flask_ext/flask_neo4j:17:

`self.db = db`

After that, the reference to the flask_module (neo4j in this case) in the authentication module (flask_ext/flask_auth.py:41) is static again

This connection is then saved as global instance?

When the connection drops this reference is no longer working and nothing is able to re-create it (as opposite connections created on endpoints are more volatitle and responsive to this kind of problems)

**Comment by mdantonio** [comment]
As additional note: this problem is occurred again today and is raising a BrokenPipeError


```
[2018-02-08 09:04:09,578] ERROR in app: Exception on /auth/profile [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_injector.py", line 128, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/restapi/protocols/bearer.py", line 105, in decorated
    if not self.authenticate(token_fn, token):
  File "/usr/local/lib/python3.6/dist-packages/restapi/protocols/bearer.py", line 46, in authenticate
    return verify_token_callback(token)
  File "/usr/local/lib/python3.6/dist-packages/restapi/services/authentication/__init__.py", line 317, in verify_token
    self._user = self.get_user_object(payload=payload)
  File "/usr/local/lib/python3.6/dist-packages/restapi/services/authentication/neo4j.py", line 37, in get_user_object
    user = self.db.User.nodes.get(uuid=payload['user_id'])
  File "/usr/local/lib/python3.6/dist-packages/neomodel/match.py", line 507, in get
    result = self.query_cls(self).build_ast()._execute()
  File "/usr/local/lib/python3.6/dist-packages/neomodel/match.py", line 411, in _execute
    results, _ = db.cypher_query(query, self._query_params)
  File "/usr/local/lib/python3.6/dist-packages/neomodel/util.py", line 28, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/neomodel/util.py", line 99, in cypher_query
    response = session.run(query, params)
  File "/usr/local/lib/python3.6/dist-packages/neo4j/v1/api.py", line 304, in run
    self._connection.send()
  File "/usr/local/lib/python3.6/dist-packages/neo4j/bolt/connection.py", line 240, in send
    self.socket.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 965, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python3.6/ssl.py", line 935, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 636, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe
```

Followed by:

```
2018-02-08 09:06:14,310 [INFO    restapi.flask_ext:112] Connected! authenticator
2018-02-08 09:06:14,313 [ERROR   restapi.services.authentication:98] Broken auth backend:
[<class 'BrokenPipeError'>] [Errno 32] Broken pipe
2018-02-08 09:06:14,313 [CRITICAL restapi.services.authentication:99] Please reinitialize backend tables
2018-02-08 09:06:14,313 [ERROR   restapi.rest.definition:328] ['Server authentication misconfiguration']


```

**Comment by pdonorio** [comment]
Could you remind me to talk about this tomorrow?

**Comment by mdantonio** [comment]
Of course

**Comment by mdantonio** [comment]
After some checks the current backend implementation is quite good...

The problem seems to arise from Neomodel, not handling neo4j that abruptly closed the connection

Broken Pipe = Your server process has received a SIGPIPE writing to a socket. This usually happens when you write to a socket fully closed on the other (client) side. This might be happening when a client program doesn't wait till all the data from the server is received and simply closes a socket (using close function).

Maybe an upgrade of both neomodel and neo4j may fix the problem?

**Comment by mdantonio** [comment]
This error confirms the previous considerations (I never read this before, something changed with 0.6.1 but it seems the same problem... still waiting for an upgrade of neo4j/neomodel to hope to fix the issue)

`<class 'neo4j.exceptions.ServiceUnavailable'> Failed to read from defunct connection Address(host='172.21.0.2', port=7687)`

**Comment by pdonorio** [comment]
Do we leave this open?

**Comment by mdantonio** [comment]
yes, unfortunately the problem is still here

**Comment by pdonorio** [comment]
No luck yet?

**Comment by mdantonio** [comment]
In the last couple of months we had no more problems on this... but i don't know why, maybe only luck

I will re-open when new cases will occur
