### ISSUE TITLE
BUG: rapydo update on local branches

### ISSUE THREAD

**Issue by mdantonio** [rapydo/issues#99]
```
$ rapydo update

2018-04-13 09:32:40,082 [INFO    controller.app:59] Do request: update
2018-04-13 09:32:40,363 [INFO    controller.gitter:243] Updating origin build-templates (branch 0.6.0)
2018-04-13 09:32:41,210 [INFO    controller.gitter:243] Updating origin frontend (branch master)
2018-04-13 09:32:42,091 [INFO    controller.gitter:243] Updating origin main (branch issue79)
Traceback (most recent call last):
 File "/usr/local/bin/rapydo", line 9, in <module>
   load_entry_point('rapydo-controller==0.6.0', 'console_scripts', 'rapydo')()
 File "/usr/local/lib/python3.5/dist-packages/controller/__main__.py", line 22, in main
   Application(arguments)
 File "/usr/local/lib/python3.5/dist-packages/controller/app.py", line 49, in __init__
File "/usr/local/lib/python3.5/dist-packages/git/cmd.py", line 418, in wait
   raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
 cmdline: git pull -v origin issue79
 stderr: 'fatal: Couldn't find remote ref issue79'
```

**Comment by mdantonio** [comment]
Now rapydo update raises an error echoing the Gitter exception, but continues with the update operations

(maybe this should be a log.warning instead a log.error... but i prefer to put more emphasis on the problem when occurring)
